### ISSUE TITLE
SOCKS5 Proxy Server

### ISSUE THREAD

**Issue by currowth** [mr-canoehead/vpn_client_gateway#10]
Can you add support for socks5 proxy server? It would be great for getting specific applications to go through the vpn.

**Comment by mr-canoehead** [comment]
Can you please describe the setup you envision? Haven't worked with socks5 at all, so I'm not familiar with it. Would it be socks5 connections instead of VPN (i.e. switching servers connects to a different socks5 server), or a socks5 proxy running on the Pi accepting connections and forwarding traffic to a single socks5 server over the VPN (same socks5 server regardless of which VPN server is used)?

Thanks,
Chris

**Comment by mr-canoehead** [comment]
Closing issue due to lack of feedback. Feel free to email me if you wish to discuss this feature request.
